name: python_git

channels:
  - defaults

dependencies:
  - jupyterlab=1.1.4
  - pandas=0.25.1
  - pip=19.2.3
  - python=3.7
  - python-graphviz=0.8
  - numpy
  - scipy

  - pip:
    - click==7.0
    - pre-commit==1.18.3
    - matplotlib==3.1.1
    - nbsphinx==0.4.2
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3



